# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Point_Table' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Point_Table
    pod 'Alamofire'
    pod 'IQKeyboardManagerSwift'
    pod 'MBProgressHUD', '~> 1.1.0'
    pod 'EMAlertController'
    pod 'Kingfisher', '~> 5.0'
    pod 'SkyFloatingLabelTextField', '~> 3.0'
    pod 'Stripe'
    pod 'Fabric', '~> 1.10.2'
    pod 'Crashlytics', '~> 3.14.0'
    pod 'Firebase/Crashlytics'
    pod 'GooglePlaces'
    pod 'GoogleMaps'
    pod 'CCBottomRefreshControl'

end
